public class GraphGenerator {

    public static void main(String[] args) {
        // ASK USER FOR GRAPH SIZE

        // RANDOMLY CREATE COORDS FOR EACH NODE (WITHIN BOUNDS)
        // RANDOMLY ASSIGN ADJACENT NODES TO EACH NODE (HOW TO ENSURE THAT
        // GRAPH IS CONNECTED?)

        // ASK USER YES/NO IF THEY WANT TO OVERRIDE A GRAPH FILE THAT ALREADY EXISTS
    }
}
